#pragma once

#define AXFX_REVERBHI_EXP_EARLY_MODE_5MS    0
#define AXFX_REVERBHI_EXP_EARLY_MODE_10MS   1
#define AXFX_REVERBHI_EXP_EARLY_MODE_15MS   2
#define AXFX_REVERBHI_EXP_EARLY_MODE_20MS   3
#define AXFX_REVERBHI_EXP_EARLY_MODE_25MS   4
#define AXFX_REVERBHI_EXP_EARLY_MODE_30MS   5
#define AXFX_REVERBHI_EXP_EARLY_MODE_35MS   6
#define AXFX_REVERBHI_EXP_EARLY_MODE_40MS   7

#define AXFX_REVERBHI_EXP_FUSED_MODE_OLD_AXFX   0
#define AXFX_REVERBHI_EXP_FUSED_MODE_METAL_TANK 1
#define AXFX_REVERBHI_EXP_FUSED_MODE_SMALL_ROOM 2
#define AXFX_REVERBHI_EXP_FUSED_MODE_LARGE_ROOM 3
#define AXFX_REVERBHI_EXP_FUSED_MODE_HALL       4
#define AXFX_REVERBHI_EXP_FUSED_MODE_CAVERNOUS  5
